### PR TITLE
Bypass the permission check for anonymous users in template filters

### PR DESCRIPTION
**Pull request by mdj2**

### CODE REVIEW

**Comment by wylee** [comment]
I'm curious as to why a falsey value would ever be passed to one of these template filters?

**Comment by wylee** [comment]
What do you think about this, which would mirror the logic in the view decorator?:

```python
        @wraps(perm_func)
        def filter_func(user, instance=NO_VALUE):
            if not allow_anonymous and user.is_anonymous():
                return False
            test = ... (same as before from here down)
```

**Comment by mdj2** [comment]
> I'm curious as to why a falsey value would ever be passed to one of these template filters.

You pass `None` as a user object in many of the tests, so I figured that was the behavior you wanted. I can kinda see the utility in that if you have a null-able FK to a user. Then you don't need an extra check in your template when you do something like `some_object.user|can_do_something`.

> What do you think about this, which would mirror the logic in the view decorator?:

Tomayto, tomahto.

**Comment by wylee** [comment]
I used None in some of the tests instead of Users out of laziness I guess. I think they should probably be changed to pass Users (which I'll volunteer to do).

**Pull request closed without merging**
